name: 'Check Github Organization Settings PRs'
on:
  pull_request:
    paths:
      - 'org/*'
      - 'toc/TOC.md'
      - 'toc/working-groups/*.md'
      - '.github/workflows/org-management-check-prs.yml'
jobs:
  org-config-generation-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/checkout@v3
        with:
          path: community
      - name: Generate github org configuration
        run: |
          python -m pip install --upgrade pip
          pip install -r community/org/requirements.txt
          python community/org/org_management.py -o cloudfoundry.out.yml -b branchprotection.out.yml
